#! /bin/zsh

bspc config border_width        	0
bspc config window_gap				12

bspc config split_ratio         	0.30
bspc config focus_follows_pointer 	false
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true

bspc monitor -d TERMINALS CODE WEB SOUND GAMES FILES TORRENTS MUSIC MEDIA

bspc rule -a subl3 						desktop=^2
bspc rule -a Google-chrome-stable		desktop=^3
bspc rule -a pavucontrol 				desktop=^4
bspc rule -a ts3client_linux_amd64 		desktop=^4
bspc rule -a Steam 						desktop=^5 follow=no
bspc rule -a thunar 					floating=on
bspc rule -a nautilus 					floating=on
bspc rule -a file-roller 				floating=on
bspc rule -a Skype 						floating=on
panel &
compton --vsync opengl-swc -c &

urxvt &
subl3 &
pavucontrol &
teamspeak3 &
ts3server start
setxkbmap -model pc104 -layout us,ru -option grp:rctrl_toggle
wmname LG3D